import { api } from "@/lib/api";
import type { Address, AuthResponse, Banner, BlogPost, ChatMessage, MyReview, CheckoutResponse, Combo, Coupon, GoogleReview, HomeSection, Order, OrderItemInput, OrderQuote, PageSection, Pagination, ResolvedLocation, Product, Review, Settings, SiteMedia, SupportOpening, SupportReply, User } from "@/types/api";

type Params = Record<string, string | number | boolean | undefined | null>;
const data = async <T>(request: Promise<{ data: T }>) => (await request).data;
export const queryKeys = { myReviews: ["reviews", "mine"] as const, settings: ["settings"] as const, categories: ["categories"] as const, categoryTree: ["categories", "tree"] as const, products: (p: Params = {}) => ["products", p] as const, product: (id: string) => ["product", id] as const, home: ["home"] as const, wishlist: ["wishlist"] as const, orders: ["orders"] as const, blog: ["blog"] as const, stores: ["stores"] as const, gardenServices: ["garden-services"] as const, gifting: ["gifting"] as const, press: ["press"] as const, combos: ["combos"] as const, combo: (id: string) => ["combo", id] as const, pageSections: (page = "home") => ["page-sections", page] as const };
export const settingsApi = { get: () => data<Settings>(api.get("/settings")), geocode: (q: string) => data<unknown>(api.get("/settings/geocode", { params: { q } })), reverseGeocode: (lat: number, lon: number) => data<ResolvedLocation>(api.get("/settings/reverse-geocode", { params: { lat, lon } })) };
export const categoriesApi = { list: () => data<import("@/types/api").Category[]>(api.get("/categories")), tree: () => data<import("@/types/api").Category[]>(api.get("/categories/tree")) };
export const brandsApi = { list: () => data<import("@/types/api").Brand[]>(api.get("/brands")) };
export const productsApi = { list: (params: Params = {}) => data<Product[] | Pagination<Product>>(api.get("/products", { params })), get: (id: string) => data<Product>(api.get(`/products/${id}`)) };
export const homeApi = { sections: () => data<HomeSection[]>(api.get("/home-sections/resolved")), banners: () => data<Banner[]>(api.get("/banners")), media: () => data<Record<string, SiteMedia[]> | SiteMedia[]>(api.get("/site-media")), recommendations: () => data<Product[] | Array<{ title?: string; products?: Product[] }>>(api.get("/recommendations/home")) };
export const combosApi = { list: () => data<Combo[]>(api.get("/combos")), get: (id: string) => data<Combo>(api.get(`/combos/${id}`)) };
export const pageSectionsApi = { list: (page = "home") => data<PageSection[]>(api.get("/page-sections", { params: { page } })) };
export const storesApi = { list: () => data<import("@/types/api").StoreLocation[]>(api.get("/stores")) };
export const gardenServicesApi = { get: () => data<{ section: import("@/types/api").GardenServiceSection; items: import("@/types/api").GardenService[]; blocks?: import("@/types/api").GardenBlocks }>(api.get("/garden-services")), enquiry: (body: { name: string; phone: string; location?: string; service?: string; note?: string }) => data<{ ok: boolean }>(api.post("/garden-services/enquiry", body)) };
export const giftingApi = { get: () => data<import("@/types/api").GiftingSection>(api.get("/gifting")) };
export const pressApi = { get: () => data<{ section: import("@/types/api").PressSection; items: import("@/types/api").PressLogo[] }>(api.get("/press")) };
export const searchApi = { search: (params: Params) => data<Product[] | Pagination<Product>>(api.get("/search", { params })), trending: () => data<{ terms: string[] }>(api.get("/search/trending")) };
export const authApi = { me: () => data<User>(api.get("/auth/me")), login: (body: { email: string; password: string }) => data<AuthResponse>(api.post("/auth/login", body)), requestOtp: (email: string) => data<Record<string, unknown>>(api.post("/auth/otp/request", { email })), verifyOtp: (email: string, code: string) => data<{ signup_token?: string; token?: string }>(api.post("/auth/otp/verify", { email, code })), register: (body: { signup_token: string; name: string; phone: string; password: string }) => data<AuthResponse>(api.post("/auth/register", body)), update: (body: Partial<User>) => data<User>(api.patch("/auth/me", body)), changePassword: (current_password: string, new_password: string) => data<{ ok: boolean; had_password: boolean }>(api.post("/auth/change-password", { current_password, new_password })), google: (credential: string) => data<AuthResponse>(api.post("/auth/google", { credential })), firebase: (id_token: string) => data<AuthResponse>(api.post("/auth/firebase", { id_token })), facebook: (access_token: string) => data<AuthResponse>(api.post("/auth/facebook", { access_token })) };
export const wishlistApi = { ids: () => data<string[] | { ids: string[] }>(api.get("/wishlist/ids")), list: () => data<Product[]>(api.get("/wishlist")), add: (id: string) => data<unknown>(api.post(`/wishlist/${id}`)), remove: (id: string) => data<unknown>(api.delete(`/wishlist/${id}`)) };
export const couponApi = { active: () => data<Coupon[]>(api.get("/coupons/active")), applicable: (body: { items: OrderItemInput[] }) => data<unknown>(api.post("/coupons/applicable", body)), validate: (body: { code: string; items: OrderItemInput[] }) => data<unknown>(api.post("/coupons/validate", body)) };
export const ordersApi = { quote: (body: { items: OrderItemInput[]; address: Address; payment_method: string; coupon_code?: string; is_gift: boolean; gift_note?: string }) => data<OrderQuote>(api.post("/orders/quote", body)), create: (body: { items: OrderItemInput[]; address: Address; payment_method: string; coupon_code?: string; is_gift: boolean; gift_note?: string }) => data<CheckoutResponse>(api.post("/orders", body)), verify: (body: { order_id: string; razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => data<Order>(api.post("/orders/verify", body)), list: () => data<Order[]>(api.get("/orders")), get: (id: string) => data<Order>(api.get(`/orders/${id}`)), cancel: (id: string, reason = "") => data<Order>(api.post(`/orders/${id}/cancel`, { reason })), invoiceUrl: (id: string) => `${api.defaults.baseURL}/orders/${id}/invoice` };
export const reviewsApi = { list: (params: Params) => data<Review[] | Pagination<Review>>(api.get("/reviews", { params })), highlights: () => data<Review[]>(api.get("/reviews/highlights")), summary: (product_id: string) => data<unknown>(api.get("/reviews/summary", { params: { product_id } })), canReview: (product_id: string) => data<{ can_review: boolean }>(api.get("/reviews/can-review", { params: { product_id } })), mine: () => data<MyReview[]>(api.get("/reviews/mine")), update: (id: string, body: Record<string, unknown>) => data<Review>(api.patch(`/reviews/${id}`, body)), remove: (id: string) => data<unknown>(api.delete(`/reviews/${id}`)), create: (body: Record<string, unknown>) => data<Review>(api.post("/reviews", body)), vote: (id: string, helpful: boolean) => data<unknown>(api.post(`/reviews/${id}/vote`, { helpful })) };
export const recommendationApi = { similar: (id: string) => data<Product[]>(api.get(`/recommendations/similar/${id}`)), cart: () => data<Product[]>(api.get("/recommendations/cart")) };
export const blogApi = { list: (params: Params = {}) => data<Pagination<BlogPost>>(api.get("/blog/posts", { params })), get: (key: string) => data<BlogPost>(api.get(`/blog/posts/${key}`)) };
export const uploadApi = {
  /** Avatars go through the signed-in customer's own upload route. */
  userImage: async (file: File) => {
    const form = new FormData();
    form.append("file", file);
    return data<{ url: string }>(api.post("/upload/user-image", form, { headers: { "Content-Type": "multipart/form-data" } }));
  },
};
export const chatApi = {
  /** Greeting + live order card + the quick actions that apply right now. */
  open: (params: { order_id?: string | undefined; product_id?: string | undefined } = {}) => data<SupportOpening>(api.get("/chat/open", { params })),
  suggestions: (order_id?: string) => data<{ questions: string[] }>(api.get("/chat/suggestions", { params: order_id ? { order_id } : {} })),
  /** Tapped chips — answered straight from the database, so they work even when the model is down. */
  action: (body: { action: string; order_id?: string | undefined; product_id?: string | undefined; reason?: string | undefined; messages?: ChatMessage[] | undefined }) =>
    data<SupportReply>(api.post("/chat/action", body)),
  send: (messages: ChatMessage[], order_id?: string) => data<SupportReply>(api.post("/chat", { messages, ...(order_id ? { order_id } : {}) })),
};
export const miscApi = { combos: () => data<Combo[]>(api.get("/combos")), googleReviews: () => data<GoogleReview[]>(api.get("/google-reviews")), googleSummary: () => data<{ count: number; average: number; breakdown?: Record<string, number> }>(api.get("/google-reviews/summary")), waitlist: (body: { product_id: string; email?: string; size_variant?: string }) => data<unknown>(api.post("/waitlist", body)), chatSuggestions: () => data<string[] | { suggestions: string[] }>(api.get("/chat/suggestions")), chat: (message: string, order_id?: string) => data<{ response?: string; reply?: string; message?: string }>(api.post("/chat", { message, ...(order_id ? { order_id } : {}) })) };
